version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  fast_api:
    image: fast-api:test
    depends_on: 
      - db
    ports:
      - 8000:8000
    volumes:
      - ../:/app
    entrypoint: uvicorn app.main:app --reload