version: "3.8"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - ${PWD}/.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:6.2.12-alpine
    restart: always

  fast_api:
    image: fast-api:test
    depends_on: 
      - db
      - redis
    ports:
      - 8000:8000
    volumes:
      - ../:/app
    entrypoint: uvicorn src.main:app --reload